Repository Terasology/ModuleTestingEnvironment, pull requests merged in 2021-07, with the labels that each got.

#55 test: register the unittest module
  src/main/java/org/terasology/moduletestingenvironment/ModuleTestingEnvironment.java
  src/test/java/org/terasology/moduletestingenvironment/ReuseEngineTest.java
  src/test/java/org/terasology/moduletestingenvironment/TestEventReceiverTest.java
Labels: Blocker

#59 chore: set scenario properties in the Config
  src/main/java/org/terasology/moduletestingenvironment/TestingStateHeadlessSetup.java
Labels: Topic: Stabilization

#58 feat!: load only modules listed as dependencies, not all in modules/
  src/main/java/org/terasology/moduletestingenvironment/MTEExtension.java
  src/main/java/org/terasology/moduletestingenvironment/ModuleTestingEnvironment.java
Labels: Topic: Stabilization

#62 fix: docs link on README.md
  README.md
Labels: Category: Doc, Size: S, Type: Bug
